# Generated by Django 5.0.14 on 2026-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Muestreo')),
                ('lote', models.CharField(default='Filadelfia - Lote Principal', max_length=100)),
                ('ph', models.FloatField(verbose_name='Nivel de pH (0-14)')),
                ('conductividad', models.FloatField(blank=True, null=True, verbose_name='Conductividad Eléctrica')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas de Campo')),
            ],
            options={
                'verbose_name': 'Registro de Suelo',
                'verbose_name_plural': 'Monitoreo de Suelos',
            },
        ),
    ]
