# Generated by Django 6.0.1 on 2026-04-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromaker_soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosuelo',
            name='humedad',
            field=models.FloatField(default=0, verbose_name='Humedad (%)'),
        ),
    ]
