# Generated by Django 5.0.14 on 2026-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField(verbose_name='Fecha Predicha')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('humedad', models.FloatField(verbose_name='Humedad (%)')),
                ('lluvia_probable', models.BooleanField(default=False, verbose_name='¿Probabilidad de Lluvia?')),
                ('nivel_riesgo_plaga', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=20)),
                ('detalles_ia', models.TextField(blank=True, null=True, verbose_name='Análisis del Modelo')),
            ],
            options={
                'verbose_name': 'Predicción Agromaker',
                'verbose_name_plural': 'Predicciones Agromaker',
            },
        ),
    ]
