# Generated by Django 5.0.14 on 2026-02-01 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromaker_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediccionclimatica',
            options={'ordering': ['-fecha_prediccion'], 'verbose_name': 'Predicción Agromaker', 'verbose_name_plural': 'Predicciones Agromaker'},
        ),
        migrations.RenameField(
            model_name='prediccionclimatica',
            old_name='detalles_ia',
            new_name='analisis_ia',
        ),
        migrations.AddField(
            model_name='prediccionclimatica',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediccionclimatica',
            name='lluvia_mm',
            field=models.FloatField(default=0.0, verbose_name='Lluvia (mm)'),
        ),
        migrations.AddField(
            model_name='prediccionclimatica',
            name='saturacion_suelo',
            field=models.FloatField(default=0.0, verbose_name='Saturación Suelo (mm)'),
        ),
        migrations.AddField(
            model_name='prediccionclimatica',
            name='semaforo_estado',
            field=models.CharField(default='VERDE', max_length=10),
        ),
    ]
