# Generated by Django 5.0.14 on 2026-02-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromaker_ai', '0002_alter_prediccionclimatica_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccionclimatica',
            name='analisis_ia',
        ),
        migrations.AddField(
            model_name='prediccionclimatica',
            name='analisis_inteligente',
            field=models.TextField(blank=True, null=True, verbose_name='Análisis Inteligente'),
        ),
        migrations.AlterField(
            model_name='prediccionclimatica',
            name='humedad',
            field=models.FloatField(default=50.0, verbose_name='Humedad (%)'),
        ),
        migrations.AlterField(
            model_name='prediccionclimatica',
            name='semaforo_estado',
            field=models.CharField(default='VERDE', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='prediccionclimatica',
            name='temperatura',
            field=models.FloatField(default=20.0, verbose_name='Temperatura (°C)'),
        ),
    ]
